### ISSUE TITLE
Big Anchorage Battle - Not Receiving Loadout

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#10]
**Originally Submitted By:** Mr. New Vegas
**Mod List Version:** .8
**Description of Bug:** After talking to the quartermaster and selecting loadout, it doesnt appear in my inventory
**Location of Bug On the Map:** Command tent
**Were You Able to Fix? (If Yes Describe in Detail):** WIP
**Supplemental Pictures/Videos (Attach to Your Post):**

**Comment by TheMrNewVegas** [comment]
Forgot who the Quartermaster was
