### ISSUE TITLE
Operation Anchorage x24 Chinese SMGs

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#11]
**Originally Submitted By:** Shartmaster
**Mod List Version:** v0.55
**Description of Bug:** The Chinese SMG found on the Anchorage Cliffs, when picked up, adds 24 to your inventory. There is no way to get ammo for them. You can drop them.
**Location of Bug On the Map:** Anchorage Cliffs, Operation Anchorage
**Were You Able to Fix? (If Yes Describe in Detail):** No
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192167358-c1c33c0e-e26c-438c-9d42-f450687d0f7b.png)
![image](https://user-images.githubusercontent.com/114360108/192167363-669fb944-e801-4264-9286-a7f8c9cdf9fc.png)

**Comment by TheMrNewVegas** [comment]
Fixed by removing AGE
