### ISSUE TITLE
Operation Anchorage Weapons Stay in Inventory After Leaving Simulation

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#12]
**Originally Submitted By:** Lilly
**Mod List Version:** .7 (had it in .1 I think)
**Description of Bug:** Any weapons picked up (Alloy Steel Sniper Rifle, Dragoon Submachine Gun, stuff like that) stay in your inventory after finishing the DLC. Cannot drop them due to them being quest items.
**Location of Bug On the Map:** The outcasts bunker
**Were You Able to Fix? (If Yes Describe in Detail):** Yes, by downloading Quest Remover Gun mod and clearing quest flags from the guns.
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192167432-b3e4b494-73c7-4215-a3cf-f01484369f1d.png)

**Comment by TheMrNewVegas** [comment]
Fixed by removing AGE
