### ISSUE TITLE
Anchorage Ending Bug

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#13]
**Originally Submitted By:** Veg
**Mod List Version:** 0.8
**Description of Bug:** When Defender Sibley decides he’s going to commit treason, he makes his little speech. However when the dialogue between the commander and him finishes, they both walk off like nothing happened. Attempting to kill sibley after this will result in all of the outcasts pouncing you

This doesn’t affect any of the loot/end game functionality of the quest but seemingly just changes the overall outcome and makes their conversation seem pretty pointless lol
**Location of Bug On the Map:** Outcast Bunker
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):**

**Comment by TheMrNewVegas** [comment]
Just need to wait a few or try reinteracting with Sibley
