### ISSUE TITLE
Consistent crash while killing ants in Springvale (0.75)

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#14]
**Originally Submitted By:** RevJimJones
**Mod List Version:** 0.75
**Description of Bug:** Using melee weapons to kill ants. Crash happens almost every kill, sometimes before the kill. Freeze game and requires task manager to end process
**Location of Bug On the Map:** Springvale
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192167524-a3cbbedc-b3df-4628-8a4d-10bc38cf82ee.png)

**Comment by TheMrNewVegas** [comment]
Removed ICE to fix this
