### ISSUE TITLE
Combat Armor

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#15]
**Originally Submitted By:** Nulla Nomen
**Mod List Version:** v.6
**Description of Bug:** Combat Armor seems to need a touchup. Don't know if it's RoyBatty, or one of the other mods. It has no DR, and its value in caps is 10x more than similar items are worth. 
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192167582-ded1a3ee-588e-4d1f-a58b-9a5920301d48.png)

**Comment by TheMrNewVegas** [comment]
Fixed by removing economy overhaul
