### ISSUE TITLE
Chinese SMG Uses Alien Disintegrator Reload Animations

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#16]
**Originally Submitted By:** Lilly
**Mod List Version:** v.7
**Description of Bug:** Chinese SMG Uses Alien Disintegrator Reload Animations
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** https://www.youtube.com/watch?v=-ot6ynjvkOA

**Comment by TheMrNewVegas** [comment]
Removing AGE fixed this
