### ISSUE TITLE
Craterside Supply is still locked on v0.75 fresh install

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#17]
**Originally Submitted By:** Bort
**Mod List Version:** .75
**Description of Bug:** New game was started;several quests were done while waiting for the supply to open. This was taken at 1pm in-game time. Craterside does not open up unless lock-picked, or "unlock"d through console.
**Location of Bug On the Map:** Megaton
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192167691-308b94aa-37b5-441c-a2ac-25cf4745b1a6.png)

**Comment by TheMrNewVegas** [comment]
Reinstall TTW, this is user side
