### ISSUE TITLE
Killing giant ants by Megaton on the road to Super-Duper Mart causes application to stop responding.

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#18]
**Originally Submitted By:** Bort
**Mod List Version:** .75
**Description of Bug:** I noticed another user was having this issue, but was under the impression it was isolated. Reporting that this bug is not an isolated incident. Currently on V 0.75. Pic related is me melee attacking, a Giant Ant with a baseball bat, and the application froze up, and stopped responding.
**Location of Bug On the Map:** ??
**Were You Able to Fix? (If Yes Describe in Detail):** ??
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192167748-5430f301-f236-4cb0-839b-3f10e3d09625.png)

**Comment by TheMrNewVegas** [comment]
Removing ICE has solved this
