### ISSUE TITLE
Paradise Falls Issues

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#19]
**Originally Submitted By:** Lilly
**Mod List Version:** v.7
**Description of Bug:** Cannot loot Ymir and Jotun is invisible
**Location of Bug On the Map:** Paradise Falls (duh)
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192167827-16521be7-ded5-464e-a390-41744bd3de99.png)

**Comment by TheMrNewVegas** [comment]
Jotun being invis should be fixed, but to loot the unlootable NPC's just change cells/fast travel away then fast travel back

**Comment by TheMrNewVegas** [comment]
Jotun being invis should be fixed, but to loot the unlootable NPC's just change cells/fast travel away then fast travel back
