### ISSUE TITLE
Fallout New Vegas PCR not supported

### ISSUE THREAD

**Issue by TDarkShadow** [TheMrNewVegas/TTWTrueVegas#2]
While a minor (and probably out of scope) issue, it's nowhere stated that the PCR version of Fallout New Vegas isn't supported.
Until last year, this is the version many East European people got when they bought Fallout New Vegas on Steam.
I recommend that's either stated in the wiki (can't make a pull request for that), or the Stock Game should be removed / replaced.

**Comment by TheMrNewVegas** [comment]
Just seeing this now I will go ahead and make that well known

**Comment by TheMrNewVegas** [comment]
The wiki has been updated under the pre installation steps thanks again for the headsup
