### ISSUE TITLE
Some coc Commands Cause 'Out-of-Map' or Black Screen

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#20]
**Originally Submitted By:** Damon22441
**Mod List Version:** .8
**Description of Bug:** some (most?) coc commands result in falling in the abyss
**Location of Bug On the Map:** from anywhere to certain locations
**Were You Able to Fix? (If Yes Describe in Detail):** Uh, no
**Supplemental Pictures/Videos (Attach to Your Post):** https://streamable.com/w6wtrn

**Comment by TheMrNewVegas** [comment]
This isn't a bug, please look up the proper COC commands
