### ISSUE TITLE
Power Armor Movement Sounds When Loading Save

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#21]
**Originally Submitted By:** Lilly
**Mod List Version:** .8
**Description of Bug:** Wearing a suit of power armor then loading a different save where you are not will still have the sound of power armor. Including a new game. Taking off the armor and loading fixes the issue.
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** https://www.youtube.com/watch?v=zOfCed-86H4

**Comment by TheMrNewVegas** [comment]
Removed PAMS
