### ISSUE TITLE
Dirty Water gives two empty bottles per 1 water

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#22]
**Originally Submitted By:** RevJimJones
**Mod List Version:** 0.8 (and earlier versions too)
**Description of Bug:** drinking 1 bottle of dirty water adds two bottles to the inventory, typically an Empty Soda Bottle and some other kind of bottle (video shows scotch bottles, but also adds sunset sas, vodka and others).
**Location of Bug On the Map:** In inventory
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** https://youtu.be/hRYqBzmEZdQ

**Comment by TheMrNewVegas** [comment]
Removed Bottle that Water and its TTW patch
