### ISSUE TITLE
Two Different items called Nuka cola dark.

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#23]
**Originally Submitted By:** RevJimJones
**Mod List Version:** 0.8
**Description of Bug:** Two items with different stats are both called Nuka Cola dark. One is under Aid/Drinks and its base ID is "6F0012D6 aaaNukaColaDark". The other is categorized as Aid/Aid (with stimpacks and stuff) and has ID "2102D7C NukaColaDark". The first one is associated with recipes, the other one is not
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):**

**Comment by TheMrNewVegas** [comment]
Added patch for Nuka Cola Imports TTW & correctly modified priority for Imports & Nuka World
