### ISSUE TITLE
Screaming Ants in Marigold Metro Hatchery

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#24]
**Originally Submitted By:** RevJimJones
**Mod List Version:** 0.8
**Description of Bug:** Some of the fire ants (just the soldiers?) are using generic human combat barks like "Whoa" "Watch Out!" while in combat.
**Location of Bug On the Map:** Marigold Station and Hatchery
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** https://youtu.be/Kwz1Vhs9hkQ

**Comment by TheMrNewVegas** [comment]
This is due to the throwing knives making your PC make noise
