### ISSUE TITLE
Duplicate Ammo Types

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#25]
**Originally Submitted By:** Lilly
**Mod List Version:** v.7
**Description of Bug:** Duplicates of ammo types. (5.56 AP vs 5.56, Armor Piercing) Only difference is one uses slightly less materials than the other.
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** deactivate the mod "Supplemental Ammo Crafting"
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192167996-49e1f39e-3ff2-4247-ae38-17b9a3a8cb0c.png)

![image](https://user-images.githubusercontent.com/114360108/192167996-49e1f39e-3ff2-4247-ae38-17b9a3a8cb0c.png)

**Comment by TheMrNewVegas** [comment]
Removed supplemental ammo crafting plugin
