### ISSUE TITLE
Eyeless Horrors

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#26]
**Originally Submitted By:** SexyThighs
**Mod List Version:** 
**Description of Bug:** A lot of the preset faces in race/sex menu are eyeless, one is missing his hair textures. Even once selected and out of character creation they continue to be eyeless.
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** Fix? Not that i could find, tried starting a new game several times to see if it persisted, it did. 
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192168043-e6cea66f-cd05-4a43-b97a-f2e275791f34.png)

![image](https://user-images.githubusercontent.com/114360108/192168041-a2076fd9-bc02-4a6c-be84-614eafeb2551.png)

![image](https://user-images.githubusercontent.com/114360108/192168029-c8721c28-cc7f-4e3e-bf8c-316dd44f6c1a.png)

**Comment by TheMrNewVegas** [comment]
We are in the process of fixing this but it is on the modder's side of things

**Comment by TheMrNewVegas** [comment]
The associated Dragbodies mods will be removed in .9+

**Comment by TheMrNewVegas** [comment]
We wont be adding these mods back
