### ISSUE TITLE
Animation Bug for Flare Gun v0.8 list

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#27]
**Originally Submitted By:** Bort
**Mod List Version:** .8
**Description of Bug:** Flare gun will bob in and out of camera perspective in 1st person while aiming for extended periods. Basically disappear, and reappear while aiming. I don't remember this being an issue in my last playthrough on v0.75.
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):**

**Comment by TheMrNewVegas** [comment]
Fixed with removal of clean anims possibly
