### ISSUE TITLE
Brotherhood T51 vs T51 PA have different stats

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#28]
**Originally Submitted By:** RevJimJones
**Mod List Version:** 0.8
**Description of Bug:** Brotherhood T51 has DT and no DR, regular T51 has slightly lower DT and lots of DR
**Location of Bug On the Map:** various, inventory, workbench
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192168100-9c675cbc-e1f5-4c3d-a37a-3515973628f7.png)
![image](https://user-images.githubusercontent.com/114360108/192168095-f62140c3-aa38-403e-9991-b7bbf197be38.png)
![image](https://user-images.githubusercontent.com/114360108/192168102-6ea9e42a-d82d-4cb7-886f-e1c954fe0457.png)

**Comment by TheMrNewVegas** [comment]
Not a bug or balancing issue more just a choice of which youd prefer
