### ISSUE TITLE
ironsights are off

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#29]
**Originally Submitted By:** Handwran
**Mod List Version:** ??
**Description of Bug:** FO3 Hunting rifle iron sights do not line up, causing you to miss.
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192168147-6e18d461-0a36-4daf-af1d-34032a65d998.png)
![image](https://user-images.githubusercontent.com/114360108/192168150-f83859cf-e06b-46f1-b085-2546344b68d3.png)
![image](https://user-images.githubusercontent.com/114360108/192168155-492424fa-5084-4130-9bd0-aae60267dd00.png)
![image](https://user-images.githubusercontent.com/114360108/192168151-03f5da16-9f8e-49cc-83f5-48448ce15c3a.png)
![image](https://user-images.githubusercontent.com/114360108/192168153-761f78c0-2db9-49b3-94ee-3c798b0f3688.png)

**Comment by TheMrNewVegas** [comment]
Currently a bug with FNV Clean Animations Pt 2, we'l just have to live with it until its updated
