### ISSUE TITLE
Missing Pool Triangle Model or Texture

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#3]
**Originally Submitted By:** Lilly
**Mod List Version:** .2
**Description of Bug:** Big ! on pool table in Rivet City Market, behind Flak and Shrapnel's store
**Location of Bug On the Map:** Rivet City Market, behind Flak and Shrapnel's store
**Were You Able to Fix? (If Yes Describe in Detail):** No
**Supplemental Pictures/Videos (Attach to Your Post):**
![image](https://user-images.githubusercontent.com/114360108/192166474-fabf3790-3d38-45d9-a01b-9841b0f7a4da.png)

**Comment by TheMrNewVegas** [comment]
Fixed by removing the folder in Precision Clutter
