### ISSUE TITLE
Bugged Magazine Textures

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#31]
**Originally Submitted By:** OmegaMercenary
**Mod List Version:** .8
**Description of Bug:** When looking at reloaded magazines at certain angles they show up with an odd looking texture.
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):**
![image](https://user-images.githubusercontent.com/114360108/192638490-6602c0eb-f19b-4b92-b265-13006c2be3bc.png)

**Comment by TheMrNewVegas** [comment]
Fixed with separating patches from main files
