### ISSUE TITLE
Bobblehead - Survival Doesn't Go on Megaton Display

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#32]
**Originally Submitted By:** Lilly
**Mod List Version:** v.86
**Description of Bug:** Can't put the survival bobblehead on the megaton house display
**Location of Bug On the Map:** I wonder (Megaton)
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):**
![image](https://user-images.githubusercontent.com/114360108/192638692-11130c38-1e97-4e51-a014-4dd7bae285a4.png)
![image](https://user-images.githubusercontent.com/114360108/192638680-3b337d52-81f5-4c9f-9efe-e328557c24de.png)

**Comment by TheMrNewVegas** [comment]
Issue with TTW interiors and its outdated nature, removing it

**Comment by TheMrNewVegas** [comment]
We are removing TTW Interiors permanently
