### ISSUE TITLE
Service Rifle Reflex Sight Changes Model

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#33]
**Originally Submitted By:** Lilly
**Mod List Version:** v.86
**Description of Bug:** Service Rifle Reflex Sight Changes Model
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):**
![image](https://user-images.githubusercontent.com/114360108/192638771-9aab8759-65ef-49f4-a22e-a019009e9384.png)
![image](https://user-images.githubusercontent.com/114360108/192638781-52c35558-9ba6-4918-8784-f0cf6a4ffcc5.png)

**Comment by TheMrNewVegas** [comment]
Will fix later
