### ISSUE TITLE
Handbottled Water

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#34]
**Originally Submitted By:** Decayz
**Mod List Version:** v.85
**Description of Bug:** Not able to receive filled water bottles when using the fill feature, it just uses the empty bottles and doesn't give me any water back.
**Location of Bug On the Map:** Anywhere
**Were You Able to Fix? (If Yes Describe in Detail):** No
**Supplemental Pictures/Videos (Attach to Your Post):** https://cdn.discordapp.com/attachments/1024461980997800016/1024461981513678878/no_fill_water.mp4

**Comment by TheMrNewVegas** [comment]
Removed mod and added Water Overhaul for .9+
