### ISSUE TITLE
Head Goes Boom When Decompressing in Mothership Zeta

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#36]
**Originally Posted By:** Lilly
**Mod List Version:** v.85 or whatever hotfix we're on
**Description of Bug:** While wearing the space suit, your head still explodes from the decompression sequence in Mothership Zeta.
**Location of Bug On the Map:** Decompression Chamber
**Were You Able to Fix? (If Yes Describe in Detail):** Yes, use TGM in console and you won't die.
**Supplemental Pictures/Videos (Attach to Your Post):** https://www.youtube.com/watch?v=DXUXcaiosn0

**Comment by TheMrNewVegas** [comment]
Fixed by removed Tammers NIF TTW Patch
