### ISSUE TITLE
Scope Overlay Issue

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#4]
**Originally Submitted By:** Lilly
**Mod List Version:** .2
**Description of Bug:** Scope overlay is very broken. Using Little Rock after killing Arkansas (just got that joke) in Minefield and the scope overlay is very broken. I think it is because I'm on ultrawide.
**Location of Bug On the Map:** Everywhere
**Were You Able to Fix? (If Yes Describe in Detail)**: No
**Supplemental Pictures/Videos (Attach to Your Post)**
![image](https://user-images.githubusercontent.com/114360108/192166894-5d5eaf9b-cf04-4228-87b5-bfb0b01232c0.png)

**Comment by TheMrNewVegas** [comment]
Go to FOV Slider and change Scope Scissoring to 0 to fix it
