### ISSUE TITLE
CTD while unequipping backpack

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#40]
**Originally Submitted By:** TheMrNewVegas
**Mod List Version:** ??
**Description of Bug:** CTD while unequipping backpack, Think s6s spice of life/spice of life itself adds this I’ll look into it
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):**

**Comment by TheMrNewVegas** [comment]
Save bloat issue
