### ISSUE TITLE
Duplicate Bandages

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#41]
**Originally Submitted By:** RevJimJones
**Mod List Version:** .9
**Description of Bug:** Duplicate Items for bandages. One is added by "Bleedout.esp" and another by "Aid Addon.esp" (this can't be used in any recipes)
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):**

**Comment by TheMrNewVegas** [comment]
NaB
