### ISSUE TITLE
Some Nuka Cola Dehydrate

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#42]
**Originally Submitted By:** RevJimJones
**Mod List Version:** .9
**Description of Bug:** the Nuka Cherry, Wild, Grape, Orange, EDIT: and Dark added AEW.esp all make you thirstier (+H20) where as other Nuka Cola relieve thirst (-H20)
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):**

**Comment by TheMrNewVegas** [comment]
Intended
