### ISSUE TITLE
Tenpenny Towers bug, can’t turn in quest

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#43]
**Originally Submitted By:** fayraz
**Mod List Version:** .85
**Description of Bug:** So I killed Roy and his other ghoul friends but the quest is telling me to both go back to Chief Gustavo AND to either help or kill Roy. And Gustavo has no option to turn in the quest
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):**

**Comment by TheMrNewVegas** [comment]
Fixed with AEW
