### ISSUE TITLE
Tranquility lane after chinese invasion exit stuck in lounger

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#44]
**Originally Submitted By:** Salty Australian
**Mod List Version:** .9
**Description of Bug:** When trying to exit the lounger i am unable to due to me not being changed back to my original race and being stuck as a child.
**Location of Bug On the Map:** Vault 112
**Were You Able to Fix? (If Yes Describe in Detail):** Reloading the game after saving in the lounger seems to have let me exit
**Supplemental Pictures/Videos (Attach to Your Post):**

**Comment by TheMrNewVegas** [comment]
Self resolving issue
