### ISSUE TITLE
Text Clutter in VW

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#45]
**Originally Submitted By:** m0nk
**Mod List Version:** .9
**Description of Bug:** Layered/Duplicate Text only under V/W.
**Location of Bug On the Map:** In Pipboy menu
**Were You Able to Fix? (If Yes Describe in Detail):** In The MCM Menu, Go to Enhanced Item Info, There is an Option Labeled "Value/Weight Ratio" under the "VATS Menu" Section. Make sure it is Unchecked.
**Supplemental Pictures/Videos (Attach to Your Post):**
![image](https://user-images.githubusercontent.com/114360108/195961267-fd105070-66fc-4271-8d63-7f1795764533.png)

**Comment by TheMrNewVegas** [comment]
Removed Enhanced Item Info
