### ISSUE TITLE
buffout kills you if you are too irradiated

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#46]
**Originally Submitted By:** Juniiorr
**Mod List Version:** .9
**Description of Bug:** if you use a buffout and receive enough radiation to reduce your health below 61, your character will die when the buffout expires
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** https://www.youtube.com/watch?v=aOJvz5SWWcU

**Comment by TheMrNewVegas** [comment]
Buffout kills you if you buff your health using it and already have critically low health
