### ISSUE TITLE
Unable to complete Tenpenny Tower quest

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#47]
**Originally Submitted By:** Kangarule
**Mod List Version:** .85
**Description of Bug:** After killing Roy Phillips and attempting to return to Tenpenny Tower to tell security chief Gustavo that you've dealt with their ghoul problem he doesn't have the dialogue option to complete the quest.
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):**
![image](https://user-images.githubusercontent.com/114360108/195961347-e771ff73-f5cc-45a2-9666-9fe9cb7dd3b0.png)
![image](https://user-images.githubusercontent.com/114360108/195961341-6c68c613-2a7b-4087-9a52-4d45dd4c2ca1.png)
![image](https://user-images.githubusercontent.com/114360108/195961369-1c0bcb0e-a1cc-4260-bf89-de3e65fc0dbf.png)

**Comment by TheMrNewVegas** [comment]
Fixed by removing AEW
