### ISSUE TITLE
Tale of two wastelands overlaps with pause menu

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#48]
**Originally Submitted By:** Salty Australian
**Mod List Version:** ???
**Description of Bug:** When pausing the game it works functionally but looks horrible with the text overlapping
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):**
![image](https://user-images.githubusercontent.com/114360108/195961422-159f89c6-5617-43ed-afdc-d654d9f71bf7.png)

**Comment by TheMrNewVegas** [comment]
Fixed in .95
