### ISSUE TITLE
Service Rifle Janky animation

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#50]
**Originally Submitted By:** Juniiorr
**Mod List Version:** .9
**Description of Bug:** 
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** https://www.youtube.com/watch?v=TjmoG9g94jQ

**Comment by TheMrNewVegas** [comment]
Fixed by removing clean animations
