### ISSUE TITLE
Night vision Goggles has its own visual effect

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#51]
**Originally Submitted By:** Juniiorr
**Mod List Version:** 0.94
**Description of Bug:** Night vision Goggles(10079056) and Reinforced Night vision Goggles(10079057) from TaleOfTwoWasterlands.esm has its own permanent night vision visual effect instead of using the Enhanced Vision features
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** https://www.youtube.com/watch?v=HKPyBTLoX9Q

**Comment by TheMrNewVegas** [comment]
Just double tap N
