### ISSUE TITLE
Audio Levels Dips During Hair Style Selection

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#52]
**Originally Submitted By:** Me! (Lilly)
**Mod List Version:** v.95
**Description of Bug:** Audio Levels Dips During Hair Style Selection
**Location of Bug On the Map:** Character Creation inside Vault 101
**Were You Able to Fix? (If Yes Describe in Detail):** No
**Supplemental Pictures/Videos (Attach to Your Post):** I apologize for the song
https://www.youtube.com/watch?v=BVNeU-gyfvY

**Comment by TheMrNewVegas** [comment]
booboo
