### ISSUE TITLE
NVMIM - Missing Hotfix and Patch

### ISSUE THREAD

**Issue by SentaiBrad** [TheMrNewVegas/TTWTrueVegas#56]
https://www.nexusmods.com/newvegas/mods/74295?tab=files

At the bottom, uploaded Oct 16th.

![image](https://user-images.githubusercontent.com/26223818/197176305-b083e4ee-e025-469f-988c-56ce0c4719e1.png)

**Comment by TheMrNewVegas** [comment]
NVMIM has been removed
