### ISSUE TITLE
FO3 Scope Problem

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#6]
**Originally Submitted By:** Damon22441
**Mod List Version:** .2
**Description of Bug:** Scope jpg blocking sight/ no crosshair (See image) for ALL FO3 weapon scopes. NV weapons are fine.
**Location of Bug On the Map:** 
**Were You Able to Fix? (If Yes Describe in Detail):** No.
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192167100-1003c273-5828-4665-b7df-ad0d9f0f17bc.png)

**Comment by TheMrNewVegas** [comment]
Fixed by prioritizing mods over others
