### ISSUE TITLE
MO2 alphabetical order 

### ISSUE THREAD

**Issue by hcooper0207** [TheMrNewVegas/TTWTrueVegas#62]
Hey! 

First of all, thanks for all the work you've put into the modpack. I've run an issue however. It appears that Wabbajack has installed my ModOrganiser load order in alphabetical order, which means TTW crashes after the opening slide show. Is there a load order that I can manually follow to order it? 

Thanks so much.

**Comment by azhais** [comment]
Did you sort your load order?   Instructions have you hit sort a couple of times before starting up the first time.

**Comment by TheMrNewVegas** [comment]
![image](https://user-images.githubusercontent.com/112358568/198854322-42584ad8-9c8a-45af-bb0f-868efb50388e.png)
You can press the priority button here until it sorts by priority ascending (0,1,2,3 and so forth)
