### ISSUE TITLE
Locked up Craterside Supply

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#7]
**Originally Submitted By:** Veg
**Mod List Version:** ??
**Description of Bug:** Cant even force unlock it lol
**Location of Bug On the Map:** Craterside Supply and Rivet City
**Were You Able to Fix? (If Yes Describe in Detail):** ??
**Supplemental Pictures/Videos (Attach to Your Post):**

**Comment by TheMrNewVegas** [comment]
This is due to an improper installation of TTW on the player's side
