### ISSUE TITLE
Can't Trade Pre-War Books to Scribe Yearning

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#8]
**Originally Submitted By:** Shartmaster
**Mod List Version:** v0.55
**Description of Bug:** The pre-war books with readable content cannot be given to Scribe Yearning in Arlington library. 
**Location of Bug On the Map:** Arlington Library
**Were You Able to Fix? (If Yes Describe in Detail):** You can spawn (unreadable) pre-war books to trade in but it's not a great solution.
**Supplemental Pictures/Videos (Attach to Your Post):**

**Comment by TheMrNewVegas** [comment]
Shift+Left Click to change books into prewar books
