### ISSUE TITLE
Naked Rivet City Security

### ISSUE THREAD

**Issue by LillyBird69** [TheMrNewVegas/TTWTrueVegas#9]
**Originally Submitted By:** Lilly
**Mod List Version:** v.7
**Description of Bug:** Most (not all) of the generic guards at Rivet City are naked
**Location of Bug On the Map:** Rivet City
**Were You Able to Fix? (If Yes Describe in Detail):** 
**Supplemental Pictures/Videos (Attach to Your Post):** 
![image](https://user-images.githubusercontent.com/114360108/192167243-2679630f-9b52-4eb1-82f4-b366ea326a39.png)

**Comment by TheMrNewVegas** [comment]
This is due to not putting TTW at the top of Load Order
